"""Compile the canonical YAML model into strict legacy proxy configurations.

This is a migration aid, not the native RetailPrintGuard runtime format.  It
never reads the database URL environment variable and never emits credentials.
"""

from __future__ import annotations

import argparse
import os
import re
from dataclasses import dataclass
from pathlib import Path
from uuid import uuid4

from retailprintguard.common.config import DeviceConfig, DeviceType, Settings, load_settings


class LegacyConfigError(ValueError):
    """The canonical configuration cannot be represented faithfully."""


@dataclass(frozen=True, slots=True)
class CompiledLegacyConfigs:
    files: dict[str, str]


def compile_legacy_configs(settings: Settings) -> CompiledLegacyConfigs:
    files: dict[str, str] = {}
    pos_devices = [
        device
        for device in settings.devices
        if device.enabled and device.type is DeviceType.POS
    ]
    rch_devices = [
        device
        for device in settings.devices
        if device.enabled and device.type is DeviceType.RCH
    ]
    if pos_devices:
        files["printproxy.conf"] = _compile_printproxy(settings, pos_devices)
    if len(rch_devices) > 1:
        raise LegacyConfigError(
            "commercialRCHproxy supports one device per process; compile each RCH route separately"
        )
    if rch_devices:
        files["commercialrchproxy.conf"] = _compile_commercialrchproxy(
            settings, rch_devices[0]
        )
    if not files:
        raise LegacyConfigError("no enabled POS or RCH device can be compiled")
    return CompiledLegacyConfigs(files)


def _compile_printproxy(settings: Settings, devices: list[DeviceConfig]) -> str:
    client_sets = {tuple(str(item) for item in device.allowed_clients) for device in devices}
    network_sets = {tuple(str(item) for item in device.allowed_networks) for device in devices}
    if len(client_sets) != 1 or len(network_sets) != 1:
        raise LegacyConfigError(
            "legacy printproxy has one global ACL; all enabled POS routes must use identical ACLs"
        )
    allowed_clients = next(iter(client_sets))
    allowed_networks = next(iter(network_sets))
    values = {
        "PROXY_PROTOCOL": "raw",
        "DELIVERY_MODE": "transparent_duplex",
        "LISTEN_IP": _csv(str(device.listen_ip) for device in devices),
        "LISTEN_PORT": _csv(str(device.listen_port) for device in devices),
        "PRINTER_IP": _csv(str(device.target_ip) for device in devices),
        "PRINTER_PORT": _csv(str(device.target_port) for device in devices),
        "DATA_DIR": _path(settings.archive_root / "legacy-printproxy" / "jobs"),
        "SPOOL_DIR": _path(settings.spool_root / "legacy-printproxy"),
        "LOG_DIR": _path(settings.log_root / "printproxy"),
        "JOB_END_MODE": "connection_close",
        "SPLIT_ON_ESCPOS_CUT": "no",
        "CONNECT_TIMEOUT": _number(settings.proxy.connect_timeout_seconds),
        "FORWARD_TIMEOUT": _number(settings.proxy.forward_timeout_seconds),
        "PRINTER_RESPONSE_TIMEOUT": _number(
            settings.proxy.response_tail_timeout_seconds
        ),
        "SESSION_IDLE_TIMEOUT": _number(settings.proxy.session_idle_timeout_seconds),
        "CHUNK_SIZE": str(settings.proxy.read_chunk_bytes),
        "MAX_CONCURRENT_CLIENTS": str(settings.proxy.max_connections),
        "SHUTDOWN_GRACE_SECONDS": _number(settings.proxy.shutdown_grace_seconds),
        "HASH_ALGORITHM": "sha256",
        "ENABLE_HASH_CHAIN": "yes",
        "ENABLE_HMAC": "yes",
        "ALLOWED_NETWORKS": ",".join(allowed_networks),
        "ALLOWED_CLIENTS": ",".join(allowed_clients),
        "ENABLE_RETENTION": "no" if settings.retention.spool_days == 0 else "yes",
        "RETENTION_DAYS": str(settings.retention.spool_days or 365),
        "DEBUG_HEXDUMP": "no",
        "ENABLE_FILE_LOG": "yes",
    }
    return _render(
        "Generated by RetailPrintGuard; strict KEY=VALUE, not a shell script.", values
    )


def _compile_commercialrchproxy(settings: Settings, device: DeviceConfig) -> str:
    values = {
        "LISTEN_IP": str(device.listen_ip),
        "LISTEN_PORT": str(device.listen_port),
        "PRINTER_IP": str(device.target_ip),
        "PRINTER_PORT": str(device.target_port),
        "OUTPUT_DIR": _path(
            settings.archive_root / "legacy-commercialrchproxy" / device.id / "jobs"
        ),
        "LOG_DIR": _path(settings.log_root / "commercialrchproxy" / device.id),
        "TIMEZONE": settings.timezone,
        "CONFIG_VERSION": "1",
        "CONNECTION_TIMEOUT_SEC": _number(settings.proxy.connect_timeout_seconds),
        "RESPONSE_TIMEOUT_SEC": _number(settings.proxy.response_tail_timeout_seconds),
        "JOB_IDLE_TIMEOUT_MS": "1000",
        "BUFFER_SIZE": str(settings.proxy.read_chunk_bytes),
        "MAX_CONNECTIONS": str(settings.proxy.max_connections),
        "PRINTER_CONNECT_ATTEMPTS": "1",
        "PRINTER_CONNECT_RETRY_DELAY_SEC": "1",
        "STORAGE_FAILURE_POLICY": settings.proxy.storage_failure_policy,
        "FSYNC_ON_CLOSE": "true",
        "PRESERVE_TIMELINE": "true",
        "CALCULATE_SHA256": "true",
        "MAX_CAPTURE_EVENTS": str(settings.proxy.capture_queue_max_events),
        "SAVE_RAW": "true",
        "SAVE_TECHNICAL_TXT": "true",
        "SAVE_CLEAN_TXT": "true",
        "SAVE_PDF": "true",
        "SAVE_JSON": "true",
        "HASH_ALGORITHM": "sha256",
        "DEBUG": "false",
        "DEBUG_HEXDUMP": "false",
        "DEBUG_PCAP": "false",
        "LOG_PAYLOAD": "false",
        "LOG_LEVEL": "INFO",
        "RETENTION_DAYS": str(settings.retention.spool_days),
        "MAX_PAYLOAD_BYTES": "67108864",
        "RENDERER_PAPER_WIDTH_MM": "79.5",
        "RENDERER_CHARACTERS_PER_LINE": "48",
        "SHUTDOWN_GRACE_SEC": _number(settings.proxy.shutdown_grace_seconds),
    }
    return _render(
        "Generated by RetailPrintGuard for one commercialRCHproxy process.", values
    )


def write_legacy_configs(
    compiled: CompiledLegacyConfigs,
    output_directory: Path,
    *,
    overwrite: bool = False,
) -> list[Path]:
    output_directory.mkdir(mode=0o750, parents=True, exist_ok=True)
    if output_directory.is_symlink() or not output_directory.is_dir():
        raise LegacyConfigError(f"unsafe output directory: {output_directory}")
    written: list[Path] = []
    for filename, content in compiled.files.items():
        destination = output_directory / filename
        if destination.exists() and not overwrite:
            raise FileExistsError(f"refusing to overwrite {destination}")
        temporary = output_directory / f".{filename}.{uuid4().hex}.tmp"
        descriptor = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640)
        try:
            payload = content.encode("utf-8")
            view = memoryview(payload)
            while view:
                count = os.write(descriptor, view)
                if count <= 0:
                    raise OSError("short write while compiling legacy configuration")
                view = view[count:]
            os.fsync(descriptor)
        except BaseException:
            os.close(descriptor)
            temporary.unlink(missing_ok=True)
            raise
        else:
            os.close(descriptor)
        os.replace(temporary, destination)
        written.append(destination)
    return written


def _render(comment: str, values: dict[str, str]) -> str:
    lines = [f"# {comment}", "# Contains endpoint and operational values only."]
    for key, value in values.items():
        if not re.fullmatch(r"[A-Z][A-Z0-9_]{1,63}", key):
            raise LegacyConfigError(f"unsafe legacy key: {key}")
        _validate_scalar(key, value)
        lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


def _validate_scalar(key: str, value: str) -> None:
    if any(character in value for character in ("\r", "\n", "\0")):
        raise LegacyConfigError(f"{key} contains a forbidden control character")
    if value != value.strip():
        raise LegacyConfigError(f"{key} contains leading or trailing whitespace")
    if not re.fullmatch(r"[A-Za-z0-9_./,:+@-]*", value):
        raise LegacyConfigError(f"{key} cannot be represented safely in strict KEY=VALUE")


def _csv(values: object) -> str:
    return ",".join(values)  # type: ignore[arg-type]


def _number(value: float) -> str:
    return format(value, "g")


def _path(value: Path) -> str:
    rendered = value.as_posix()
    if len(rendered) >= 3 and rendered[1:3] == ":/":
        rendered = rendered[2:]
    return rendered


def cli() -> int:
    parser = argparse.ArgumentParser(description="Compile RetailPrintGuard YAML for legacy relays")
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--output-directory", required=True, type=Path)
    parser.add_argument("--overwrite", action="store_true")
    arguments = parser.parse_args()
    settings = load_settings(arguments.config)
    compiled = compile_legacy_configs(settings)
    for path in write_legacy_configs(
        compiled,
        arguments.output_directory,
        overwrite=arguments.overwrite,
    ):
        print(path)
    return 0


__all__ = [
    "CompiledLegacyConfigs",
    "LegacyConfigError",
    "compile_legacy_configs",
    "write_legacy_configs",
]
