"""initial normalized evidence schema

Revision ID: 29517f373309
Revises:
Create Date: 2026-08-13 01:03:45.138283
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

import retailprintguard.db.types

revision: str = "29517f373309"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("device_type", sa.String(length=16), nullable=False),
        sa.Column("parser_kind", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("bidirectional", sa.Boolean(), nullable=False),
        sa.Column("listen_ip", sa.String(length=45), nullable=False),
        sa.Column("listen_port", sa.Integer(), nullable=False),
        sa.Column("target_ip", sa.String(length=45), nullable=False),
        sa.Column("target_port", sa.Integer(), nullable=False),
        sa.Column("non_sensitive_config", sa.JSON(), nullable=False),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("external_id", name=op.f("uq_devices_external_id")),
        sa.UniqueConstraint(
            "listen_ip", "listen_port", name=op.f("uq_devices_listen_ip_listen_port")
        ),
        sa.UniqueConstraint(
            "target_ip", "target_port", name=op.f("uq_devices_target_ip_target_port")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "fraud_rules",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("code", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_rules")),
        sa.UniqueConstraint("code", name=op.f("uq_fraud_rules_code")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "hash_chain_heads",
        sa.Column("scope", sa.String(length=191), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column("updated_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("scope", name=op.f("pk_hash_chain_heads")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "analysis_watermarks",
        sa.Column("service", sa.String(length=64), nullable=False),
        sa.Column("cursor_timestamp", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("cursor_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("processed_count", sa.BigInteger(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("service", name=op.f("pk_analysis_watermarks")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "parser_versions",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("build_sha256", sa.String(length=64), nullable=False),
        sa.Column("protocol", sa.String(length=64), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("installed_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parser_versions")),
        sa.UniqueConstraint(
            "name",
            "version",
            "build_sha256",
            name=op.f("uq_parser_versions_name_version_build_sha256"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "roles",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "active_parser_versions",
        sa.Column("parser_name", sa.String(length=128), nullable=False),
        sa.Column(
            "parser_version_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False
        ),
        sa.Column("activated_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("activation_reason", sa.String(length=191), nullable=False),
        sa.ForeignKeyConstraint(
            ["parser_version_id"],
            ["parser_versions.id"],
            name=op.f("fk_active_parser_versions_parser_version_id_parser_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("parser_name", name=op.f("pk_active_parser_versions")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "users",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=191), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("last_login_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("password_changed_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "audit_log",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("chain_scope", sa.String(length=191), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("actor_user_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("event_type", sa.String(length=96), nullable=False),
        sa.Column("resource_type", sa.String(length=96), nullable=False),
        sa.Column("resource_id", sa.String(length=191), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column("occurred_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("previous_record_hash", sa.String(length=64), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        sa.UniqueConstraint(
            "chain_scope", "sequence", name=op.f("uq_audit_log_chain_scope_sequence")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_log_occurred", ["occurred_at"], unique=False)
        batch_op.create_index(
            "ix_audit_log_resource", ["resource_type", "resource_id"], unique=False
        )

    op.create_table(
        "device_status",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("device_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("observed_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_connection_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("last_print_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("last_response_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("spool_bytes", sa.BigInteger(), nullable=False),
        sa.Column("pending_imports", sa.Integer(), nullable=False),
        sa.Column("service_version", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_status_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_status")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("device_status", schema=None) as batch_op:
        batch_op.create_index(
            "ix_device_status_device_observed", ["device_id", "observed_at"], unique=False
        )

    op.create_table(
        "document_correlations",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column(
            "transaction_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False
        ),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("matched_criteria", sa.JSON(), nullable=False),
        sa.Column("unmatched_criteria", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "reviewed_by_user_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column("review_decision", sa.String(length=64), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_document_correlations_reviewed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_correlations")),
        sa.UniqueConstraint(
            "transaction_id",
            "algorithm_version",
            "input_fingerprint",
            name="uq_corr_tx_algorithm_input",
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("document_correlations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_correlations_score", ["score", "created_at"], unique=False
        )

    op.create_table(
        "fraud_rule_versions",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("fraud_rule_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("implementation_version", sa.String(length=64), nullable=False),
        sa.Column("configuration_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("threshold", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("weight", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("effective_from", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("effective_until", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column(
            "created_by_user_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_fraud_rule_versions_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fraud_rule_id"],
            ["fraud_rules.id"],
            name=op.f("fk_fraud_rule_versions_fraud_rule_id_fraud_rules"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_rule_versions")),
        sa.UniqueConstraint(
            "fraud_rule_id", "version", name=op.f("uq_fraud_rule_versions_fraud_rule_id_version")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("fraud_rule_versions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fraud_rule_version_config",
            ["fraud_rule_id", "configuration_fingerprint"],
            unique=False,
        )
    op.create_table(
        "fraud_whitelists",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("entry_key", sa.String(length=64), nullable=False),
        sa.Column("fraud_rule_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_value", sa.String(length=512), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("valid_from", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("valid_until", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column(
            "created_by_user_id",
            retailprintguard.db.types.UUIDBinary(length=16),
            nullable=False,
        ),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_fraud_whitelists_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fraud_rule_id"],
            ["fraud_rules.id"],
            name=op.f("fk_fraud_whitelists_fraud_rule_id_fraud_rules"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_whitelists")),
        sa.UniqueConstraint("entry_key", name=op.f("uq_fraud_whitelists_entry_key")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("fraud_whitelists", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fraud_whitelists_active_window",
            ["active", "valid_from", "valid_until"],
            unique=False,
        )
        batch_op.create_index(
            "ix_fraud_whitelists_scope", ["scope_type", "scope_value"], unique=False
        )
    op.create_table(
        "import_batches",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_instance", sa.String(length=128), nullable=False),
        sa.Column("source_root", sa.Text(), nullable=False),
        sa.Column(
            "requested_by_user_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("ended_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("scanned_count", sa.Integer(), nullable=False),
        sa.Column("imported_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_import_batches_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_import_batches_status_started", ["status", "started_at"], unique=False
        )

    op.create_table(
        "orders",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column(
            "source_device_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column(
            "parent_order_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("order_code", sa.String(length=128), nullable=False),
        sa.Column("table_code", sa.String(length=128), nullable=True),
        sa.Column("operator_code", sa.String(length=128), nullable=True),
        sa.Column("terminal_code", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("opened_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("closed_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("gross_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("net_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("discount_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_order_id"],
            ["orders.id"],
            name=op.f("fk_orders_parent_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_device_id"],
            ["devices.id"],
            name=op.f("fk_orders_source_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "source_device_id",
            "business_date",
            "order_code",
            name=op.f("uq_orders_source_device_id_business_date_order_code"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            "ix_orders_operator_opened", ["operator_code", "opened_at"], unique=False
        )
        batch_op.create_index("ix_orders_table_opened", ["table_code", "opened_at"], unique=False)

    op.create_table(
        "proxy_sessions",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("device_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_instance", sa.String(length=128), nullable=False),
        sa.Column("source_scope", sa.String(length=255), nullable=False),
        sa.Column("source_session_id", sa.String(length=128), nullable=False),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("client_port", sa.Integer(), nullable=True),
        sa.Column("listen_ip", sa.String(length=45), nullable=False),
        sa.Column("listen_port", sa.Integer(), nullable=False),
        sa.Column("target_ip", sa.String(length=45), nullable=False),
        sa.Column("target_port", sa.Integer(), nullable=False),
        sa.Column("started_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("ended_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("client_fin_received", sa.Boolean(), nullable=False),
        sa.Column("device_fin_received", sa.Boolean(), nullable=False),
        sa.Column("bytes_to_device", sa.BigInteger(), nullable=False),
        sa.Column("bytes_to_client", sa.BigInteger(), nullable=False),
        sa.Column("capture_complete", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_proxy_sessions_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proxy_sessions")),
        sa.UniqueConstraint(
            "source_system",
            "source_instance",
            "source_scope",
            "source_session_id",
            name=op.f(
                "uq_proxy_sessions_source_system_source_instance_source_scope_source_session_id"
            ),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("proxy_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_proxy_sessions_device_started", ["device_id", "started_at"], unique=False
        )
        batch_op.create_index(
            "ix_proxy_sessions_source_session", ["source_session_id"], unique=False
        )

    op.create_table(
        "user_roles",
        sa.Column("user_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("role_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column(
            "granted_by_user_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column("granted_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["users.id"],
            name=op.f("fk_user_roles_granted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "fraud_alerts",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column(
            "fraud_rule_version_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False
        ),
        sa.Column("correlation_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column(
            "transaction_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False
        ),
        sa.Column("finding_key", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("original_amount", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("final_amount", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("difference_amount", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("difference_percent", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("confidence", sa.SmallInteger(), nullable=False),
        sa.Column(
            "assigned_to_user_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column("taken_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("closed_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("closure_reason", sa.Text(), nullable=True),
        sa.Column("opened_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
            name=op.f("fk_fraud_alerts_assigned_to_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["correlation_id"],
            ["document_correlations.id"],
            name=op.f("fk_fraud_alerts_correlation_id_document_correlations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fraud_rule_version_id"],
            ["fraud_rule_versions.id"],
            name=op.f("fk_fraud_alerts_fraud_rule_version_id_fraud_rule_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_alerts")),
        sa.UniqueConstraint(
            "fraud_rule_version_id",
            "transaction_id",
            "finding_key",
            name=op.f("uq_fraud_alerts_fraud_rule_version_id_transaction_id_finding_key"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("fraud_alerts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fraud_alerts_severity_opened", ["severity", "opened_at"], unique=False
        )
        batch_op.create_index(
            "ix_fraud_alerts_status_opened", ["status", "opened_at"], unique=False
        )

    op.create_table(
        "print_jobs",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("device_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("session_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("source_key", sa.String(length=512), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_instance", sa.String(length=128), nullable=False),
        sa.Column("source_scope", sa.String(length=255), nullable=False),
        sa.Column("source_job_id", sa.String(length=128), nullable=False),
        sa.Column("source_schema", sa.String(length=128), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest_path", sa.Text(), nullable=False),
        sa.Column("started_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("ended_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("captured_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("boundary_source", sa.String(length=64), nullable=True),
        sa.Column("boundary_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("capture_complete", sa.Boolean(), nullable=False),
        sa.Column("timeline_complete", sa.Boolean(), nullable=False),
        sa.Column("import_status", sa.String(length=32), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("imported_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_print_jobs_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["proxy_sessions.id"],
            name=op.f("fk_print_jobs_session_id_proxy_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_print_jobs")),
        sa.UniqueConstraint("source_key", name=op.f("uq_print_jobs_source_key")),
        sa.UniqueConstraint(
            "source_system",
            "source_instance",
            "source_scope",
            "source_job_id",
            name=op.f("uq_print_jobs_source_system_source_instance_source_scope_source_job_id"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("print_jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_print_jobs_device_started", ["device_id", "started_at"], unique=False
        )
        batch_op.create_index(
            "ix_print_jobs_import_status", ["import_status", "captured_at"], unique=False
        )

    op.create_table(
        "documents",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("device_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("session_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("job_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("source_document_key", sa.String(length=191), nullable=False),
        sa.Column("document_type", sa.String(length=48), nullable=False),
        sa.Column("subtype", sa.String(length=128), nullable=False),
        sa.Column("external_document_code", sa.String(length=128), nullable=True),
        sa.Column("order_code", sa.String(length=128), nullable=True),
        sa.Column("table_code", sa.String(length=128), nullable=True),
        sa.Column("operator_code", sa.String(length=128), nullable=True),
        sa.Column("terminal_code", sa.String(length=128), nullable=True),
        sa.Column("document_timestamp", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("captured_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_documents_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["print_jobs.id"],
            name=op.f("fk_documents_job_id_print_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["proxy_sessions.id"],
            name=op.f("fk_documents_session_id_proxy_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint(
            "job_id", "source_document_key", name=op.f("uq_documents_job_id_source_document_key")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_documents_external_code", ["external_document_code"], unique=False
        )
        batch_op.create_index(
            "ix_documents_order_captured", ["order_code", "captured_at"], unique=False
        )
        batch_op.create_index(
            "ix_documents_table_captured", ["table_code", "captured_at"], unique=False
        )
        batch_op.create_index(
            "ix_documents_type_captured", ["document_type", "captured_at"], unique=False
        )
        batch_op.create_index("ix_documents_captured_cursor", ["captured_at", "id"], unique=False)

    op.create_table(
        "fraud_alert_history",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column(
            "fraud_alert_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False
        ),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("actor_user_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("previous_status", sa.String(length=32), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("occurred_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("previous_record_hash", sa.String(length=64), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_fraud_alert_history_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fraud_alert_id"],
            ["fraud_alerts.id"],
            name=op.f("fk_fraud_alert_history_fraud_alert_id_fraud_alerts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_alert_history")),
        sa.UniqueConstraint(
            "fraud_alert_id",
            "sequence",
            name=op.f("uq_fraud_alert_history_fraud_alert_id_sequence"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "raw_payloads",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("job_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("device_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("session_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("artifact_role", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=32), nullable=False),
        sa.Column(
            "payload",
            sa.LargeBinary()
            .with_variant(mysql.LONGBLOB(), "mariadb")
            .with_variant(mysql.LONGBLOB(), "mysql"),
            nullable=False,
        ),
        sa.Column("byte_count", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("source_path_sha256", sa.String(length=64), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("chain_scope", sa.String(length=191), nullable=False),
        sa.Column("chain_sequence", sa.BigInteger(), nullable=False),
        sa.Column("previous_record_hash", sa.String(length=64), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_raw_payloads_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["print_jobs.id"],
            name=op.f("fk_raw_payloads_job_id_print_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["proxy_sessions.id"],
            name=op.f("fk_raw_payloads_session_id_proxy_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_payloads")),
        sa.UniqueConstraint(
            "job_id",
            "artifact_role",
            "source_path_sha256",
            name=op.f("uq_raw_payloads_job_id_artifact_role_source_path_sha256"),
        ),
        sa.UniqueConstraint(
            "chain_scope",
            "chain_sequence",
            name=op.f("uq_raw_payloads_chain_scope_chain_sequence"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("raw_payloads", schema=None) as batch_op:
        batch_op.create_index("ix_raw_payloads_sha256", ["sha256"], unique=False)

    op.create_table(
        "system_events",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("service", sa.String(length=96), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("event_type", sa.String(length=96), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("device_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("session_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("job_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("occurred_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_system_events_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["print_jobs.id"],
            name=op.f("fk_system_events_job_id_print_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["proxy_sessions.id"],
            name=op.f("fk_system_events_session_id_proxy_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_events")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_system_events_device_occurred", ["device_id", "occurred_at"], unique=False
        )
        batch_op.create_index(
            "ix_system_events_service_occurred", ["service", "occurred_at"], unique=False
        )

    op.create_table(
        "document_correlation_members",
        sa.Column(
            "correlation_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False
        ),
        sa.Column("document_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("role", sa.String(length=48), nullable=False),
        sa.Column("contribution_score", sa.SmallInteger(), nullable=False),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["correlation_id"],
            ["document_correlations.id"],
            name=op.f("fk_document_correlation_members_correlation_id_document_correlations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_correlation_members_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "correlation_id", "document_id", name=op.f("pk_document_correlation_members")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "document_versions",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("document_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column(
            "parser_version_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False
        ),
        sa.Column("raw_payload_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("parse_run_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("version_sequence", sa.Integer(), nullable=False),
        sa.Column("parsed_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("gross_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("net_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("discount_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("tax_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("payment_method", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("encoding", sa.String(length=64), nullable=True),
        sa.Column("parse_confidence", sa.SmallInteger(), nullable=False),
        sa.Column("evidence_level", sa.String(length=32), nullable=False),
        sa.Column("source_manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("chain_scope", sa.String(length=191), nullable=False),
        sa.Column("chain_sequence", sa.BigInteger(), nullable=False),
        sa.Column("previous_record_hash", sa.String(length=64), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parser_version_id"],
            ["parser_versions.id"],
            name=op.f("fk_document_versions_parser_version_id_parser_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["raw_payloads.id"],
            name=op.f("fk_document_versions_raw_payload_id_raw_payloads"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id",
            "parser_version_id",
            "source_payload_sha256",
            name=op.f("uq_document_versions_document_id_parser_version_id_source_payload_sha256"),
        ),
        sa.UniqueConstraint(
            "document_id",
            "version_sequence",
            name=op.f("uq_document_versions_document_id_version_sequence"),
        ),
        sa.UniqueConstraint(
            "chain_scope",
            "chain_sequence",
            name=op.f("uq_document_versions_chain_scope_chain_sequence"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_versions_parsed_cursor", ["parsed_at", "id"], unique=False
        )
        batch_op.create_index(
            "ix_document_versions_parser", ["parser_version_id", "parsed_at"], unique=False
        )

    op.create_table(
        "fraud_alert_evidence",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column(
            "fraud_alert_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False
        ),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("document_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("print_job_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("raw_payload_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("artifact_path", sa.Text(), nullable=True),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_fraud_alert_evidence_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fraud_alert_id"],
            ["fraud_alerts.id"],
            name=op.f("fk_fraud_alert_evidence_fraud_alert_id_fraud_alerts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["print_job_id"],
            ["print_jobs.id"],
            name=op.f("fk_fraud_alert_evidence_print_job_id_print_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["raw_payloads.id"],
            name=op.f("fk_fraud_alert_evidence_raw_payload_id_raw_payloads"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_alert_evidence")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("fraud_alert_evidence", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fraud_alert_evidence_alert", ["fraud_alert_id", "sequence"], unique=False
        )

    op.create_table(
        "import_items",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column(
            "import_batch_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False
        ),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_instance", sa.String(length=128), nullable=False),
        sa.Column("source_scope", sa.String(length=255), nullable=False),
        sa.Column("source_job_id", sa.String(length=191), nullable=False),
        sa.Column("source_event_id", sa.String(length=191), nullable=True),
        sa.Column("artifact_role", sa.String(length=64), nullable=False),
        sa.Column("original_path", sa.Text(), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_count", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "imported_job_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column(
            "imported_document_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column("attempted_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("imported_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_items_import_batch_id_import_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["imported_document_id"],
            ["documents.id"],
            name=op.f("fk_import_items_imported_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["imported_job_id"],
            ["print_jobs.id"],
            name=op.f("fk_import_items_imported_job_id_print_jobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_items")),
        sa.UniqueConstraint(
            "source_system",
            "source_instance",
            "source_scope",
            "source_job_id",
            "artifact_role",
            name=op.f(
                "uq_import_items_source_system_source_instance_source_scope_source_job_id_artifact_role"
            ),
        ),
        sa.UniqueConstraint(
            "source_instance",
            "source_scope",
            "source_event_id",
            name=op.f("uq_import_items_source_instance_source_scope_source_event_id"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("import_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_import_items_batch_status", ["import_batch_id", "status"], unique=False
        )
        batch_op.create_index("ix_import_items_sha256", ["sha256"], unique=False)

    op.create_table(
        "order_events",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("order_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column(
            "source_document_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("operator_code", sa.String(length=128), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("previous_record_hash", sa.String(length=64), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_events_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
            name=op.f("fk_order_events_source_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_events")),
        sa.UniqueConstraint("order_id", "sequence", name=op.f("uq_order_events_order_id_sequence")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("order_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_order_events_order_occurred", ["order_id", "occurred_at"], unique=False
        )

    op.create_table(
        "stream_chunks",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("session_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("job_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("raw_payload_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("observed_sequence", sa.BigInteger(), nullable=False),
        sa.Column("direction_sequence", sa.BigInteger(), nullable=False),
        sa.Column("direction", sa.String(length=32), nullable=False),
        sa.Column("event_kind", sa.String(length=16), nullable=False),
        sa.Column("direction_offset", sa.BigInteger(), nullable=False),
        sa.Column("session_offset", sa.BigInteger(), nullable=False),
        sa.Column("received_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("received_unix_ns", sa.BigInteger(), nullable=True),
        sa.Column("monotonic_ns", sa.BigInteger(), nullable=True),
        sa.Column("forwarded_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("local_drain_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("byte_count", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.LargeBinary()
            .with_variant(mysql.LONGBLOB(), "mariadb")
            .with_variant(mysql.LONGBLOB(), "mysql"),
            nullable=False,
        ),
        sa.Column("forwarded", sa.Boolean(), nullable=False),
        sa.Column("forward_status", sa.String(length=64), nullable=False),
        sa.Column("forward_error", sa.Text(), nullable=True),
        sa.Column("previous_record_hash", sa.String(length=64), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["print_jobs.id"],
            name=op.f("fk_stream_chunks_job_id_print_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["raw_payloads.id"],
            name=op.f("fk_stream_chunks_raw_payload_id_raw_payloads"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["proxy_sessions.id"],
            name=op.f("fk_stream_chunks_session_id_proxy_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stream_chunks")),
        sa.UniqueConstraint(
            "session_id",
            "direction",
            "direction_offset",
            name=op.f("uq_stream_chunks_session_id_direction_direction_offset"),
        ),
        sa.UniqueConstraint(
            "session_id", "sequence", name=op.f("uq_stream_chunks_session_id_sequence")
        ),
        sa.UniqueConstraint(
            "session_id",
            "observed_sequence",
            name=op.f("uq_stream_chunks_session_id_observed_sequence"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("stream_chunks", schema=None) as batch_op:
        batch_op.create_index("ix_stream_chunks_job_sequence", ["job_id", "sequence"], unique=False)

    op.create_table(
        "document_lines",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column(
            "document_version_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False
        ),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("item_code", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("quantity", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("unit_price", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("original_unit_price", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("modified_unit_price", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("discount", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("surcharge", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("tax_rate", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("line_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("line_state", sa.String(length=64), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("removed", sa.Boolean(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("source_direction", sa.String(length=32), nullable=True),
        sa.Column("source_offset", sa.BigInteger(), nullable=True),
        sa.Column("source_length", sa.BigInteger(), nullable=True),
        sa.Column("source_frame_id", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_document_lines_document_version_id_document_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_lines")),
        sa.UniqueConstraint(
            "document_version_id",
            "sequence",
            name=op.f("uq_document_lines_document_version_id_sequence"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("document_lines", schema=None) as batch_op:
        batch_op.create_index("ix_document_lines_description", ["description"], unique=False)

    op.create_table(
        "order_snapshots",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("order_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("order_event_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("captured_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.Column("gross_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("net_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("discount_total", mysql.DECIMAL(precision=19, scale=4), nullable=True),
        sa.Column("lines", sa.JSON(), nullable=False),
        sa.Column("previous_record_hash", sa.String(length=64), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_event_id"],
            ["order_events.id"],
            name=op.f("fk_order_snapshots_order_event_id_order_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_snapshots_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_snapshots")),
        sa.UniqueConstraint(
            "order_id", "sequence", name=op.f("uq_order_snapshots_order_id_sequence")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "payments",
        sa.Column("id", retailprintguard.db.types.UUIDBinary(length=16), nullable=False),
        sa.Column("order_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True),
        sa.Column(
            "document_version_id", retailprintguard.db.types.UUIDBinary(length=16), nullable=True
        ),
        sa.Column("external_payment_code", sa.String(length=128), nullable=True),
        sa.Column("method", sa.String(length=128), nullable=True),
        sa.Column("amount", mysql.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("evidence_level", sa.String(length=32), nullable=False),
        sa.Column("paid_at", retailprintguard.db.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", retailprintguard.db.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "document_version_id IS NOT NULL OR order_id IS NOT NULL",
            name=op.f("ck_payments_payment_has_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_payments_document_version_id_document_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_payments_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index("ix_payments_order_paid", ["order_id", "paid_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping an initial schema does not require explicitly removing indexes.
    # MariaDB may choose an application index to enforce a foreign key and then
    # rejects DROP INDEX before DROP TABLE (error 1553).  Reverse dependency
    # order lets each table and its indexes/constraints disappear atomically.
    op.drop_table("payments")
    op.drop_table("order_snapshots")
    op.drop_table("document_lines")
    op.drop_table("stream_chunks")
    op.drop_table("order_events")
    op.drop_table("import_items")
    op.drop_table("fraud_alert_evidence")
    op.drop_table("document_versions")
    op.drop_table("document_correlation_members")
    op.drop_table("system_events")
    op.drop_table("raw_payloads")
    op.drop_table("documents")
    op.drop_table("print_jobs")
    op.drop_table("fraud_alert_history")
    op.drop_table("fraud_alerts")
    op.drop_table("user_roles")
    op.drop_table("proxy_sessions")
    op.drop_table("orders")
    op.drop_table("import_batches")
    op.drop_table("fraud_whitelists")
    op.drop_table("fraud_rule_versions")
    op.drop_table("document_correlations")
    op.drop_table("device_status")
    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("active_parser_versions")
    op.drop_table("parser_versions")
    op.drop_table("analysis_watermarks")
    op.drop_table("hash_chain_heads")
    op.drop_table("fraud_rules")
    op.drop_table("devices")
